@extends('layout.layout')
@section('title', $title)
@section('content')
<style>
.report-paper{background:#fff;width:100%;min-height:900px;padding:35px 40px;box-shadow:0 0 8px rgba(0,0,0,.15);border:1px solid #ddd}.report-header{text-align:center}.report-header h2{margin:0;font-size:24px;font-weight:bold}.report-header h3{margin:5px 0;font-size:20px;font-weight:bold}.report-summary{margin-bottom:15px;font-size:15px}.table-report{width:100%;border-collapse:collapse;font-size:13px}.table-report th,.table-report td{border:1px solid #333;padding:7px 8px}.table-report th{text-align:center;font-weight:bold}.table-report td:first-child{text-align:center;width:40px}.report-footer{margin-top:30px;font-size:12px}@media print{body *{visibility:hidden}.report-paper,.report-paper *{visibility:visible}.report-paper{position:absolute;left:0;top:0;width:100%;box-shadow:none;border:none;padding:20px}.no-print{display:none!important}}
</style>
<section class="content" style="padding-top:17px"><div class="container-fluid"><div class="card no-print"><div class="card-header"><h3 class="card-title"><i class="fas fa-calendar-alt"></i> <strong>Filter Tanggal</strong></h3></div><div class="card-body"><div class="row"><div class="col-md-3"><div class="form-group"><label>Tanggal Mulai</label><input type="date" id="reportStart" class="form-control"></div></div><div class="col-md-3"><div class="form-group"><label>Tanggal Akhir</label><input type="date" id="reportEnd" class="form-control"></div></div><div class="col-md-2"><div class="form-group"><label>&nbsp;</label><button id="reportFilter" class="btn btn-primary btn-block"><i class="fas fa-search"></i> Tampilkan</button></div></div><div class="col-md-2"><div class="form-group"><label>&nbsp;</label><button id="reportReset" class="btn btn-secondary btn-block"><i class="fas fa-sync-alt"></i> Reset</button></div></div></div></div></div><div class="card"><div class="card-header no-print"><h3 class="card-title"><i class="fas fa-list"></i> <strong>{{ $title }}</strong></h3><div class="card-tools"><button type="button" id="reportExcel" class="btn btn-success btn-sm"><i class="fas fa-file-excel"></i> Export Excel</button> <button type="button" id="reportPdf" class="btn btn-danger btn-sm"><i class="fas fa-file-pdf"></i> Export PDF</button> <button type="button" id="reportPrint" class="btn btn-secondary btn-sm"><i class="fas fa-print"></i> Print</button></div></div><div class="card-body"><div class="report-paper"><div class="report-header"><h2>WARRANTY SYSTEM</h2><h3>{{ strtoupper($title) }}</h3><p>Periode: <strong id="reportPeriod">Semua Data</strong></p></div><hr><div class="report-summary"><strong>Total Data:</strong> <span id="reportTotal">0</span>@if($reportType === 'INVOICE')<div class="row mt-3"><div class="col-md-4"><strong>Total Grand Total:</strong><br><span id="invoiceGrandTotal">Rp 0,00</span></div><div class="col-md-4"><strong>Total Paid:</strong><br><span id="invoicePaidTotal">Rp 0,00</span></div><div class="col-md-4"><strong>Total Outstanding:</strong><br><span id="invoiceOutstandingTotal">Rp 0,00</span></div></div>@endif</div><table class="table-report"><thead><tr id="reportHead"></tr></thead><tbody id="reportBody"></tbody></table><div class="report-footer">Dicetak pada: <span id="reportPrintedAt"></span></div></div></div></div></div></section>
<script>window.genericReport={url:@json($reportUrl),excelUrl:@json($exportExcelUrl),pdfUrl:@json($exportPdfUrl),type:@json($reportType)};</script>
@endsection
